# Generated by Django 6.0.5 on 2026-05-09 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('date_en', models.CharField(max_length=50)),
                ('date_uz', models.CharField(blank=True, max_length=50)),
                ('title_en', models.CharField(max_length=300)),
                ('title_uz', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('date', models.DateField()),
                ('title_en', models.CharField(max_length=300)),
                ('title_uz', models.CharField(blank=True, max_length=300)),
                ('dek_en', models.TextField(help_text='Short description / deck (English)')),
                ('dek_uz', models.TextField(blank=True, help_text='Short description / deck (Uzbek)')),
                ('tag', models.CharField(max_length=50)),
                ('read_time', models.PositiveIntegerField(help_text='Estimated reading time in minutes')),
                ('featured', models.BooleanField(default=False)),
                ('content_en', models.TextField(blank=True, help_text='Full post body (English, supports HTML)')),
                ('content_uz', models.TextField(blank=True, help_text='Full post body (Uzbek, supports HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_uz', models.CharField(blank=True, max_length=200)),
                ('kind_en', models.CharField(max_length=50)),
                ('kind_uz', models.CharField(blank=True, max_length=50)),
                ('price_en', models.CharField(max_length=50)),
                ('price_uz', models.CharField(blank=True, max_length=50)),
                ('blurb_en', models.TextField()),
                ('blurb_uz', models.TextField(blank=True)),
                ('cta_en', models.CharField(max_length=50)),
                ('cta_uz', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline_en', models.CharField(max_length=300)),
                ('tagline_uz', models.CharField(blank=True, max_length=300)),
                ('desc_en', models.TextField()),
                ('desc_uz', models.TextField(blank=True)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(max_length=50)),
                ('href', models.URLField(blank=True, default='#')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_en', models.CharField(max_length=100)),
                ('period_uz', models.CharField(blank=True, max_length=100)),
                ('description_en', models.TextField()),
                ('description_uz', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Timeline entries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UsesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_uz', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Uses categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=200)),
                ('text_uz', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='blog.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UsesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note_en', models.TextField()),
                ('note_uz', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='blog.usescategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
