# Generated by Django 6.0.5 on 2026-05-19 06:32

from django.db import migrations, models
from django.utils import timezone


def confirm_existing_subscribers(apps, schema_editor):
    Subscriber = apps.get_model('blog', 'NewsletterSubscriber')
    Subscriber.objects.filter(is_active=True).update(confirmed=True, confirmed_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_product_slug_and_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', models.TextField(blank=True, help_text='HTML or Markdown')),
                ('content_uz', models.TextField(blank=True)),
                ('content_format', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown')], default='markdown', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Now page',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(default='https://fazliddin.com')),
                ('analytics_domain', models.CharField(blank=True, help_text='Plausible domain, e.g. fazliddin.com', max_length=200)),
                ('giscus_repo', models.CharField(blank=True, help_text='user/repo', max_length=200)),
                ('giscus_repo_id', models.CharField(blank=True, max_length=100)),
                ('giscus_category_id', models.CharField(blank=True, default='General', max_length=100)),
                ('calendly_url', models.URLField(blank=True)),
                ('double_opt_in', models.BooleanField(default=True)),
                ('comments_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_en', models.CharField(max_length=200)),
                ('role_uz', models.CharField(blank=True, max_length=200)),
                ('quote_en', models.TextField()),
                ('quote_uz', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='newsletterissue',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirm_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='post',
            name='content_format',
            field=models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown')], default='html', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='series_part',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='checkout_url',
            field=models.URLField(blank=True, help_text='Stripe, Gumroad, or payment link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True, help_text='Full post body (English, supports HTML/Markdown)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_uz',
            field=models.TextField(blank=True, help_text='Full post body (Uzbek, supports HTML/Markdown)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.RunPython(confirm_existing_subscribers, migrations.RunPython.noop),
    ]
